
function PlotAvgInsideOutside_t( ...
    time_h, ...
    actvInMean, actvInSEM, actvOutMean, actvOutSEM, ...
    ctrlInMean, ctrlInSEM, ctrlOutMean, ctrlOutSEM, ...
    ctrl_start_h, actv_h, ...
    yLabelText, figTitle, outputFile, ...
    showFig, saveFig)

if ~showFig && ~saveFig
    return
end

if showFig
    figVisibility = "on";
else
    figVisibility = "off";
end

fig = figure( ...
    "Position",[100 100 900 650], ...
    "Color","w", ...
    "Visible",figVisibility);

tiledlayout(2,1, ...
    "Padding","compact", ...
    "TileSpacing","compact");

allValues = [ ...
    actvInMean - actvInSEM, actvInMean + actvInSEM, ...
    actvOutMean - actvOutSEM, actvOutMean + actvOutSEM, ...
    ctrlInMean - ctrlInSEM, ctrlInMean + ctrlInSEM, ...
    ctrlOutMean - ctrlOutSEM, ctrlOutMean + ctrlOutSEM];

yMin = min(allValues, [], "omitnan");
yMax = max(allValues, [], "omitnan");

padding = 0.1 * (yMax - yMin);
if padding == 0
    padding = 1;
end

yLimits = [yMin-padding, yMax+padding];

% -------- INSIDE --------

ax1 = nexttile;
hold(ax1,"on")

patch(ax1, ...
    [ctrl_start_h ctrl_start_h+actv_h ctrl_start_h+actv_h ctrl_start_h], ...
    [yLimits(1) yLimits(1) yLimits(2) yLimits(2)], ...
    [0.85 0.85 1], ...
    "EdgeColor","none", ...
    "FaceAlpha",0.5, ...
    "HandleVisibility","off");

fill(ax1, ...
    [time_h fliplr(time_h)], ...
    [actvInMean + actvInSEM fliplr(actvInMean - actvInSEM)], ...
    [0.6 0.6 0.6], ...
    "EdgeColor","none", ...
    "FaceAlpha",0.5, ...
    "DisplayName","Activated mean $\pm$ SEM");

plot(ax1, ...
    time_h, actvInMean, ...
    "k", ...
    "LineWidth",2, ...
    "DisplayName","Activated mean");

fill(ax1, ...
    [time_h fliplr(time_h)], ...
    [ctrlInMean + ctrlInSEM fliplr(ctrlInMean - ctrlInSEM)], ...
    [1 0.7 0.7], ...
    "EdgeColor","none", ...
    "FaceAlpha",0.4, ...
    "DisplayName","Control mean $\pm$ SEM");

plot(ax1, ...
    time_h, ctrlInMean, ...
    "r", ...
    "LineWidth",1.5, ...
    "DisplayName","Control mean");

xline(ax1,ctrl_start_h,"--k","LineWidth",1.5,"HandleVisibility","off");
xline(ax1,ctrl_start_h+actv_h,"--k","LineWidth",1.5,"HandleVisibility","off");

ylim(ax1,yLimits)
ylabel(ax1,yLabelText,"Interpreter","latex")
title(ax1,"INSIDE")
legend(ax1,"Location","best","Interpreter","latex")
grid(ax1,"on")
box(ax1,"on")

% -------- OUTSIDE --------

ax2 = nexttile;
hold(ax2,"on")

patch(ax2, ...
    [ctrl_start_h ctrl_start_h+actv_h ctrl_start_h+actv_h ctrl_start_h], ...
    [yLimits(1) yLimits(1) yLimits(2) yLimits(2)], ...
    [0.85 0.85 1], ...
    "EdgeColor","none", ...
    "FaceAlpha",0.5, ...
    "HandleVisibility","off");

fill(ax2, ...
    [time_h fliplr(time_h)], ...
    [actvOutMean + actvOutSEM fliplr(actvOutMean - actvOutSEM)], ...
    [0.6 0.6 0.6], ...
    "EdgeColor","none", ...
    "FaceAlpha",0.5, ...
    "DisplayName","Activated mean $\pm$ SEM");

plot(ax2, ...
    time_h, actvOutMean, ...
    "k", ...
    "LineWidth",2, ...
    "DisplayName","Activated mean");

fill(ax2, ...
    [time_h fliplr(time_h)], ...
    [ctrlOutMean + ctrlOutSEM fliplr(ctrlOutMean - ctrlOutSEM)], ...
    [1 0.7 0.7], ...
    "EdgeColor","none", ...
    "FaceAlpha",0.4, ...
    "DisplayName","Control mean $\pm$ SEM");

plot(ax2, ...
    time_h, ctrlOutMean, ...
    "r", ...
    "LineWidth",1.5, ...
    "DisplayName","Control mean");

xline(ax2,ctrl_start_h,"--k","LineWidth",1.5,"HandleVisibility","off");
xline(ax2,ctrl_start_h+actv_h,"--k","LineWidth",1.5,"HandleVisibility","off");

ylim(ax2,yLimits)
xlabel(ax2,"Time (h)")
ylabel(ax2,yLabelText,"Interpreter","latex")
title(ax2,"OUTSIDE")
legend(ax2,"Location","best","Interpreter","latex")
grid(ax2,"on")
box(ax2,"on")

linkaxes([ax1 ax2],"x")
sgtitle(figTitle)

if saveFig
    exportgraphics(fig, outputFile, "Resolution",300);
    savefig(fig, replace(outputFile,".png",".fig"));
end

if ~showFig
    close(fig)
end

end